#!/usr/bin/env ruby
# encoding: UTF-8

SHIM_LIB = ENV['SHIM_DEBUG'] ? 'nvshim.debug.so' : 'nvshim.so'

`sysctl hw.nvidia.version` =~ /^hw.nvidia.version: NVIDIA UNIX x86_64 Kernel Module  ([\d\.+]+)/
driver_version = $1

raise if not driver_version

libmap = <<~E
  libGL.so   libGL.so.#{driver_version}
  libGL.so.1 libGL.so.#{driver_version}
E

for lib in [
  'libGL.so.'               + driver_version,
  'libnvidia-glcore.so.'    + driver_version,
  'libnvidia-glvkspirv.so.' + driver_version,
  'libnvidia-tls.so.'       + driver_version
]
  libmap += "\n[#{lib}]\n"
  for mapped_lib in ['libc.so.6', 'libm.so.6', 'libdl.so.2', 'librt.so.1', 'libpthread.so.0']
    libmap += "#{mapped_lib} #{SHIM_LIB}\n"
  end
end

ENV['LD_LIBMAP']          = libmap
ENV['LD_32_LIBMAP']       = libmap
ENV['LD_LIBRARY_PATH']    = [__dir__ + '/build/lib64', __dir__ + '/nvidia/lib64', ENV['LD_LIBRARY_PATH']   ].compact.join(':')
ENV['LD_32_LIBRARY_PATH'] = [__dir__ + '/build/lib32', __dir__ + '/nvidia/lib32', ENV['LD_32_LIBRARY_PATH']].compact.join(':')

ENV['VK_ICD_FILENAMES']   = __dir__ + '/nv_vk_icd.json'

exec *ARGV
