#!/usr/bin/env ruby
# encoding: UTF-8

`sysctl hw.nvidia.version` =~ /^hw.nvidia.version: NVIDIA UNIX x86_64 Kernel Module  ([\d\.+]+)/
driver_version = $1

raise if not driver_version

libgl_nvidia = if ENV['SHIM_GLVND'] || driver_version.split('.').first.to_i >= 435
  "libGLX_nvidia.so.#{driver_version}"
else
  "libGL.so.#{driver_version}"
end

shim_lib = ENV['SHIM_DEBUG'] ? 'nvshim.debug.so' : 'nvshim.so'

libmap = [
   "libgl_nvidia #{libgl_nvidia}",
  ("libGL.so     #{libgl_nvidia}" if not ENV['SHIM_GLVND']),
  ("libGL.so.1   #{libgl_nvidia}" if not ENV['SHIM_GLVND']),
  '',
  "libGLX_nvidia.so.0            libGLX_nvidia.so.#{driver_version}",
  "libnvidia-ptxjitcompiler.so.1 libnvidia-ptxjitcompiler.so.#{driver_version}",
  '',
  "libc.so.6       #{shim_lib}",
  "libdl.so.2      #{shim_lib}",
  "libm.so.6       #{shim_lib}",
  "libpthread.so.0 #{shim_lib}",
  "librt.so.x      #{shim_lib}"
].compact.join("\n")

ENV['LD_LIBMAP']          = libmap
ENV['LD_32_LIBMAP']       = libmap
ENV['LD_LIBRARY_PATH']    = [__dir__ + '/build/lib64', __dir__ + '/nvidia/lib64/tls', __dir__ + '/nvidia/lib64', ENV['LD_LIBRARY_PATH']   ].compact.join(':')
ENV['LD_32_LIBRARY_PATH'] = [__dir__ + '/build/lib32', __dir__ + '/nvidia/lib32/tls', __dir__ + '/nvidia/lib32', ENV['LD_32_LIBRARY_PATH']].compact.join(':')

ENV['VK_ICD_FILENAMES']   = __dir__ + '/nv_vk_icd.json'

exec *ARGV
